Dev
aleksandr1101/TowerDefenceFGame pull request #1
Opened 2020-04-15 21:14 UTC by aleksandr1101

2020-05-06 19:57 UTC, akhtyamovpavel requested changes
В целом, хорошо!

Жду отделение логики и интерфейса, описания игровых действий, башню я даже смог поставить и замечаний в коде

Пока что за задание - 8 (больше по кодовой части)

2020-05-06 19:57 UTC, akhtyamovpavel commented on board.py
> +        self.cells.append(Cell(110, 398, 189, 473))
Лучше одним списком

2020-05-06 19:57 UTC, akhtyamovpavel commented on game.py
> +import pygame
`.DS_Store` - в `.gitignore`

2020-05-06 19:57 UTC, akhtyamovpavel commented on game.py
> +            if event.key == pygame.K_q:
Жду превращения в паттерн команду и отделения логики от интерфейса

2020-05-06 19:57 UTC, akhtyamovpavel commented on game.py
> +                    print(x, y)
Лучше вынести в отдельную функцию

2020-05-06 19:57 UTC, akhtyamovpavel commented on tower.py
> +        return eq[random.randint(0, len(eq) - 1)]
Функцию `random` лучше вынести в отдельную - генерация случайных чисел - это отдельная логика

2020-05-06 19:57 UTC, akhtyamovpavel commented on tower.py
> +            uX, uY = unit.center()
Не понимаю смысл переменных cX, cY uX, uY, лучше их переименовать

2020-05-06 19:57 UTC, akhtyamovpavel commented on tower.py
> +        eq = list()
Лучше давать осмысленные имена переменным

2020-05-06 19:57 UTC, akhtyamovpavel commented on tower.py
> +        screen.blit(pic, (self.x, self.y))
Логика связана с интерфейсом...

2020-05-06 19:57 UTC, akhtyamovpavel commented on tower.py
> +        super().__init__([1, 1, 1], tps // 2, 200, "freezing.png")
Посмотрите на паттерн FlyWeight

2020-05-06 19:57 UTC, akhtyamovpavel commented on game.py
> +                tower_type = tower.FireTowerFactory()
Лучше писать `if __name__ == '__main__'`

2020-05-19 20:23 UTC, akhtyamovpavel approved these changes
Добрый день!

Посмотрел задание, по паттернам можно было использовать больше паттернов - разные апгрейды в виде декораторов, их применение, зачисление бонусов и прочие вещи.

Поэтому за вторую и третью часть ставлю по 6, можно игру улучшать во многие стороны

2020-05-19 20:23 UTC, akhtyamovpavel commented on README.md
> +3) Декоратор, для логирования(по факту не нужен, не понятно как его по-другому 	здесь применить)
Почему других паттернов не было использовано?

2020-05-19 20:23 UTC, akhtyamovpavel commented on README.md
> +Существует 3 типа башен: стандартная(повышенный урон), замедляющая(замедление монстров), огненная(поджигает монстров), 4 типа монстров: стандартные, быстрые, плотные(много hp), боссы(очень много hp,
Удаляем `.pyc` файлы из репозитория

2020-05-19 20:23 UTC, akhtyamovpavel commented on commands.py
> +        if kt == pygame.K_q:
Лучше использовать константы, чтобы потом можно было менять управление

2020-05-19 20:23 UTC, akhtyamovpavel commented on game.py
> +            pygame.time.wait(1000)
Очень большое дублирование этой команды, стоит это сделать красивее

2020-05-19 20:23 UTC, akhtyamovpavel commented on game.py
> +        for tow in board.towers:
`tow` -> `tower`

2020-05-19 20:23 UTC, akhtyamovpavel commented on game.py
> +fonts = [game_font, info_font]
Лучше вынести в отдельную функцию

2020-05-22 14:08 UTC, Kright requested changes
папку __pycache__ спрятать под gitignore

2021-09-12 21:38 UTC, merged